// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3aX3uqQ4D5XR29e9iiQoBPrbA3xEQHpU',
    appId: '1:997133946428:web:2bcdc158a61750bd7b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    authDomain: 'dtapps-f3442.firebaseapp.com',
    storageBucket: 'dtapps-f3442.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkMEOzA2mOEwO9bWPXEx-oYikQ7TV0RiE',
    appId: '1:997133946428:android:c9300a9dd6e5ba137b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    storageBucket: 'dtapps-f3442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt887Q8SN-uiySGkeU5TZj0lzEwJAXRnE',
    appId: '1:997133946428:ios:04d6f20d8eebadc27b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    storageBucket: 'dtapps-f3442.appspot.com',
    androidClientId: '997133946428-171bm07artqpela0a6718rsdipuhvvqs.apps.googleusercontent.com',
    iosClientId: '997133946428-euu7a1ravjqb4kp1oauh7heq6ison2fc.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.dttube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt887Q8SN-uiySGkeU5TZj0lzEwJAXRnE',
    appId: '1:997133946428:ios:04d6f20d8eebadc27b7d39',
    messagingSenderId: '997133946428',
    projectId: 'dtapps-f3442',
    storageBucket: 'dtapps-f3442.appspot.com',
    androidClientId: '997133946428-171bm07artqpela0a6718rsdipuhvvqs.apps.googleusercontent.com',
    iosClientId: '997133946428-euu7a1ravjqb4kp1oauh7heq6ison2fc.apps.googleusercontent.com',
    iosBundleId: 'com.divinetechs.dttube',
  );
}
